#pragma once
///stl includes
#include <iostream>
#include <string>
#include <vector>
#include <queue>
#include <fstream>
#include <sstream>
#include <iterator>
#include <cstring>
#include <chrono>
#include <cctype>
#include <thread>
#include <map>

//linux includes
///sock_int requires:
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h> 

///mysql interfacing
#include <mysql.h>
#include <my_global.h>
#include <my_sys.h>
#include <m_string.h>
